package pruebaDeTesting

import org.apache.poi.ss.usermodel.FillPatternType
import org.apache.poi.ss.usermodel.IndexedColors
import org.apache.poi.xssf.usermodel.XSSFWorkbook
import java.io.FileOutputStream



fun archivoExcel(valor: Int, prueba: String){
    val doc = "./src/main/resources/raw/Reporte_URIDEC.xlsx"
    val output = FileOutputStream(doc)
    val dato = XSSFWorkbook()

    val titulo = dato.createSheet(/* sheetname = */ "Reporte")

    val estiloV = dato.createCellStyle()
    estiloV.fillForegroundColor = IndexedColors.GREEN.index
    estiloV.fillPattern = FillPatternType.SOLID_FOREGROUND
    val estiloR = dato.createCellStyle()
    estiloR.fillForegroundColor = IndexedColors.RED.index
    estiloR.fillPattern = FillPatternType.SOLID_FOREGROUND
    val estiloB = dato.createCellStyle()
    estiloB.fillForegroundColor = IndexedColors.GREY_50_PERCENT.index
    estiloB.fillPattern = FillPatternType.SOLID_FOREGROUND

    when(valor){
        0 -> {
            titulo.createRow(/* rownum = */ 0).createCell(/* columnIndex = */ 1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("Archivo:")
            titulo.getRow(8).createCell(2).setCellValue("Valido")
            titulo.getRow(8).createCell(3).cellStyle = estiloV
            dato.write(output)
            dato.close()
        }
        1 -> {
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Fallo")
            titulo.getRow(4).createCell(3).cellStyle = estiloR
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Nul--")
            titulo.getRow(5).createCell(3).cellStyle = estiloB
            titulo.createRow(6).createCell(0).setCellValue("Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Nul--")
            titulo.getRow(6).createCell(3).cellStyle = estiloB
            titulo.createRow(7).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Nul--")
            titulo.getRow(7).createCell(3).cellStyle = estiloB
            titulo.createRow(8).createCell(0).setCellValue("Archivo:")
            titulo.getRow(8).createCell(2).setCellValue("Nul--")
            titulo.getRow(8).createCell(3).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        2 ->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Fallo")
            titulo.getRow(5).createCell(3).cellStyle = estiloR
            titulo.createRow(6).createCell(0).setCellValue("Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Null---")
            titulo.getRow(6).createCell(3).cellStyle = estiloB
            titulo.createRow(7).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Null---")
            titulo.getRow(7).createCell(3).cellStyle = estiloB
            titulo.createRow(8).createCell(0).setCellValue("Archivo:")
            titulo.getRow(8).createCell(2).setCellValue("Null---")
            titulo.getRow(8).createCell(3).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        3->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(1).setCellValue("Valido")
            titulo.getRow(4).createCell(3).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Fallo")
            titulo.getRow(6).createCell(3).cellStyle = estiloR
            titulo.createRow(7).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Null---")
            titulo.getRow(7).createCell(3).cellStyle = estiloB
            titulo.createRow(8).createCell(0).setCellValue("Archivo:")
            titulo.getRow(8).createCell(2).setCellValue("Null---")
            titulo.getRow(8).createCell(3).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        4 ->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Fallo")
            titulo.getRow(7).createCell(3).cellStyle = estiloR
            titulo.createRow(8).createCell(0).setCellValue("Archivo:")
            titulo.getRow(8).createCell(2).setCellValue("Null---")
            titulo.getRow(8).createCell(3).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        5 ->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("Archivo:")
            titulo.getRow(8).createCell(2).setCellValue("Fallo")
            titulo.getRow(8).createCell(3).cellStyle = estiloR
            dato.write(output)
            dato.close()
        }
        6->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Fallo")
            titulo.getRow(4).createCell(3).setCellValue("Fallo")
            titulo.getRow(4).createCell(4).setCellValue("Fallo")
            titulo.getRow(4).createCell(5).setCellValue("Fallo")
            titulo.getRow(4).createCell(6).setCellValue("Fallo")
            titulo.getRow(4).createCell(7).setCellValue("Fallo")
            titulo.getRow(4).createCell(8).setCellValue("Fallo")
            titulo.getRow(4).createCell(9).setCellValue("Fallo")
            titulo.getRow(4).createCell(10).cellStyle = estiloR
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Null--")
            titulo.getRow(5).createCell(3).setCellValue("Null--")
            titulo.getRow(5).createCell(4).setCellValue("Null--")
            titulo.getRow(5).createCell(5).setCellValue("Null--")
            titulo.getRow(5).createCell(6).setCellValue("Null--")
            titulo.getRow(5).createCell(7).setCellValue("Null--")
            titulo.getRow(5).createCell(8).setCellValue("Null--")
            titulo.getRow(5).createCell(9).setCellValue("Null--")
            titulo.getRow(5).createCell(10).cellStyle = estiloB
            titulo.createRow(6).createCell(0).setCellValue("Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Null--")
            titulo.getRow(6).createCell(3).setCellValue("Null--")
            titulo.getRow(6).createCell(4).setCellValue("Null--")
            titulo.getRow(6).createCell(5).setCellValue("Null--")
            titulo.getRow(6).createCell(6).setCellValue("Null--")
            titulo.getRow(6).createCell(7).setCellValue("Null--")
            titulo.getRow(6).createCell(8).setCellValue("Null--")
            titulo.getRow(6).createCell(9).setCellValue("Null--")
            titulo.getRow(6).createCell(10).cellStyle = estiloB
            titulo.createRow(7).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Null--")
            titulo.getRow(7).createCell(3).setCellValue("Null--")
            titulo.getRow(7).createCell(4).setCellValue("Null--")
            titulo.getRow(7).createCell(5).setCellValue("Null--")
            titulo.getRow(7).createCell(6).setCellValue("Null--")
            titulo.getRow(7).createCell(7).setCellValue("Null--")
            titulo.getRow(7).createCell(8).setCellValue("Null--")
            titulo.getRow(7).createCell(9).setCellValue("Null--")
            titulo.getRow(7).createCell(10).cellStyle = estiloB
            titulo.createRow(8).createCell(0).setCellValue("Archivo:")
            titulo.getRow(8).createCell(2).setCellValue("Null--")
            titulo.getRow(8).createCell(3).setCellValue("Null--")
            titulo.getRow(8).createCell(4).setCellValue("Null--")
            titulo.getRow(8).createCell(5).setCellValue("Null--")
            titulo.getRow(8).createCell(6).setCellValue("Null--")
            titulo.getRow(8).createCell(7).setCellValue("Null--")
            titulo.getRow(8).createCell(8).setCellValue("Null--")
            titulo.getRow(8).createCell(9).setCellValue("Null--")
            titulo.getRow(8).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        7->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("B Salir:")
            titulo.getRow(5).createCell(2).setCellValue("Fallo")
            titulo.getRow(5).createCell(3).setCellValue("Fallo")
            titulo.getRow(5).createCell(4).setCellValue("Fallo")
            titulo.getRow(5).createCell(5).setCellValue("Fallo")
            titulo.getRow(5).createCell(6).setCellValue("Fallo")
            titulo.getRow(5).createCell(7).setCellValue("Fallo")
            titulo.getRow(5).createCell(8).setCellValue("Fallo")
            titulo.getRow(5).createCell(9).setCellValue("Fallo")
            titulo.getRow(5).createCell(10).cellStyle = estiloR
            titulo.createRow(6).createCell(0).setCellValue("Opciones:")
            titulo.getRow(6).createCell(2).setCellValue("Null--")
            titulo.getRow(6).createCell(3).setCellValue("Null--")
            titulo.getRow(6).createCell(4).setCellValue("Null--")
            titulo.getRow(6).createCell(5).setCellValue("Null--")
            titulo.getRow(6).createCell(6).setCellValue("Null--")
            titulo.getRow(6).createCell(7).setCellValue("Null--")
            titulo.getRow(6).createCell(8).setCellValue("Null--")
            titulo.getRow(6).createCell(9).setCellValue("Null--")
            titulo.getRow(6).createCell(10).cellStyle = estiloB
            titulo.createRow(7).createCell(0).setCellValue("Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Null--")
            titulo.getRow(7).createCell(3).setCellValue("Null--")
            titulo.getRow(7).createCell(4).setCellValue("Null--")
            titulo.getRow(7).createCell(5).setCellValue("Null--")
            titulo.getRow(7).createCell(6).setCellValue("Null--")
            titulo.getRow(7).createCell(7).setCellValue("Null--")
            titulo.getRow(7).createCell(8).setCellValue("Null--")
            titulo.getRow(7).createCell(9).setCellValue("Null--")
            titulo.getRow(7).createCell(10).cellStyle = estiloB
            titulo.createRow(8).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(8).createCell(2).setCellValue("Null--")
            titulo.getRow(8).createCell(3).setCellValue("Null--")
            titulo.getRow(8).createCell(4).setCellValue("Null--")
            titulo.getRow(8).createCell(5).setCellValue("Null--")
            titulo.getRow(8).createCell(6).setCellValue("Null--")
            titulo.getRow(8).createCell(7).setCellValue("Null--")
            titulo.getRow(8).createCell(8).setCellValue("Null--")
            titulo.getRow(8).createCell(9).setCellValue("Null--")
            titulo.getRow(8).createCell(10).cellStyle = estiloB
            titulo.createRow(9).createCell(0).setCellValue("Archivo:")
            titulo.getRow(9).createCell(2).setCellValue("Null--")
            titulo.getRow(9).createCell(3).setCellValue("Null--")
            titulo.getRow(9).createCell(4).setCellValue("Null--")
            titulo.getRow(9).createCell(5).setCellValue("Null--")
            titulo.getRow(9).createCell(6).setCellValue("Null--")
            titulo.getRow(9).createCell(7).setCellValue("Null--")
            titulo.getRow(9).createCell(8).setCellValue("Null--")
            titulo.getRow(9).createCell(9).setCellValue("Null--")
            titulo.getRow(9).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        8->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Crear Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Fallo")
            titulo.getRow(6).createCell(3).setCellValue("Fallo")
            titulo.getRow(6).createCell(4).setCellValue("Fallo")
            titulo.getRow(6).createCell(5).setCellValue("Fallo")
            titulo.getRow(6).createCell(6).setCellValue("Fallo")
            titulo.getRow(6).createCell(7).setCellValue("Fallo")
            titulo.getRow(6).createCell(8).setCellValue("Fallo")
            titulo.getRow(6).createCell(9).setCellValue("Fallo")
            titulo.getRow(6).createCell(10).cellStyle = estiloR
            titulo.createRow(7).createCell(0).setCellValue("Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Null--")
            titulo.getRow(7).createCell(3).setCellValue("Null--")
            titulo.getRow(7).createCell(4).setCellValue("Null--")
            titulo.getRow(7).createCell(5).setCellValue("Null--")
            titulo.getRow(7).createCell(6).setCellValue("Null--")
            titulo.getRow(7).createCell(7).setCellValue("Null--")
            titulo.getRow(7).createCell(8).setCellValue("Null--")
            titulo.getRow(7).createCell(9).setCellValue("Null--")
            titulo.getRow(7).createCell(10).cellStyle = estiloB
            titulo.createRow(8).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(8).createCell(2).setCellValue("Null--")
            titulo.getRow(8).createCell(3).setCellValue("Null--")
            titulo.getRow(8).createCell(4).setCellValue("Null--")
            titulo.getRow(8).createCell(5).setCellValue("Null--")
            titulo.getRow(8).createCell(6).setCellValue("Null--")
            titulo.getRow(8).createCell(7).setCellValue("Null--")
            titulo.getRow(8).createCell(8).setCellValue("Null--")
            titulo.getRow(8).createCell(9).setCellValue("Null--")
            titulo.getRow(8).createCell(10).cellStyle = estiloB
            titulo.createRow(9).createCell(0).setCellValue("Archivo:")
            titulo.getRow(9).createCell(2).setCellValue("Null--")
            titulo.getRow(9).createCell(3).setCellValue("Null--")
            titulo.getRow(9).createCell(4).setCellValue("Null--")
            titulo.getRow(9).createCell(5).setCellValue("Null--")
            titulo.getRow(9).createCell(6).setCellValue("Null--")
            titulo.getRow(9).createCell(7).setCellValue("Null--")
            titulo.getRow(9).createCell(8).setCellValue("Null--")
            titulo.getRow(9).createCell(9).setCellValue("Null--")
            titulo.getRow(9).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        9->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Crear Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("B Regresar:")
            titulo.getRow(7).createCell(2).setCellValue("Fallo")
            titulo.getRow(7).createCell(3).setCellValue("Fallo")
            titulo.getRow(7).createCell(4).setCellValue("Fallo")
            titulo.getRow(7).createCell(5).setCellValue("Fallo")
            titulo.getRow(7).createCell(6).setCellValue("Fallo")
            titulo.getRow(7).createCell(7).setCellValue("Fallo")
            titulo.getRow(7).createCell(8).setCellValue("Fallo")
            titulo.getRow(7).createCell(9).setCellValue("Fallo")
            titulo.getRow(7).createCell(10).cellStyle = estiloR
            titulo.createRow(8).createCell(0).setCellValue("Formulario:")
            titulo.getRow(8).createCell(2).setCellValue("Null--")
            titulo.getRow(8).createCell(3).setCellValue("Null--")
            titulo.getRow(8).createCell(4).setCellValue("Null--")
            titulo.getRow(8).createCell(5).setCellValue("Null--")
            titulo.getRow(8).createCell(6).setCellValue("Null--")
            titulo.getRow(8).createCell(7).setCellValue("Null--")
            titulo.getRow(8).createCell(8).setCellValue("Null--")
            titulo.getRow(8).createCell(9).setCellValue("Null--")
            titulo.getRow(8).createCell(10).cellStyle = estiloB
            titulo.createRow(9).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(9).createCell(2).setCellValue("Null--")
            titulo.getRow(9).createCell(3).setCellValue("Null--")
            titulo.getRow(9).createCell(4).setCellValue("Null--")
            titulo.getRow(9).createCell(5).setCellValue("Null--")
            titulo.getRow(9).createCell(6).setCellValue("Null--")
            titulo.getRow(9).createCell(7).setCellValue("Null--")
            titulo.getRow(9).createCell(8).setCellValue("Null--")
            titulo.getRow(9).createCell(9).setCellValue("Null--")
            titulo.getRow(9).createCell(10).cellStyle = estiloB
            titulo.createRow(10).createCell(0).setCellValue("Archivo:")
            titulo.getRow(10).createCell(2).setCellValue("Null--")
            titulo.getRow(10).createCell(3).setCellValue("Null--")
            titulo.getRow(10).createCell(4).setCellValue("Null--")
            titulo.getRow(10).createCell(5).setCellValue("Null--")
            titulo.getRow(10).createCell(6).setCellValue("Null--")
            titulo.getRow(10).createCell(7).setCellValue("Null--")
            titulo.getRow(10).createCell(8).setCellValue("Null--")
            titulo.getRow(10).createCell(9).setCellValue("Null--")
            titulo.getRow(10).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        10->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Crear Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("B Salir:")
            titulo.getRow(7).createCell(2).setCellValue("Fallo")
            titulo.getRow(7).createCell(3).setCellValue("Fallo")
            titulo.getRow(7).createCell(4).setCellValue("Fallo")
            titulo.getRow(7).createCell(5).setCellValue("Fallo")
            titulo.getRow(7).createCell(6).setCellValue("Fallo")
            titulo.getRow(7).createCell(7).setCellValue("Fallo")
            titulo.getRow(7).createCell(8).setCellValue("Fallo")
            titulo.getRow(7).createCell(9).setCellValue("Fallo")
            titulo.getRow(7).createCell(10).cellStyle = estiloR
            titulo.createRow(8).createCell(0).setCellValue("Formulario:")
            titulo.getRow(8).createCell(2).setCellValue("Null--")
            titulo.getRow(8).createCell(3).setCellValue("Null--")
            titulo.getRow(8).createCell(4).setCellValue("Null--")
            titulo.getRow(8).createCell(5).setCellValue("Null--")
            titulo.getRow(8).createCell(6).setCellValue("Null--")
            titulo.getRow(8).createCell(7).setCellValue("Null--")
            titulo.getRow(8).createCell(8).setCellValue("Null--")
            titulo.getRow(8).createCell(9).setCellValue("Null--")
            titulo.getRow(8).createCell(10).cellStyle = estiloB
            titulo.createRow(9).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(9).createCell(2).setCellValue("Null--")
            titulo.getRow(9).createCell(3).setCellValue("Null--")
            titulo.getRow(9).createCell(4).setCellValue("Null--")
            titulo.getRow(9).createCell(5).setCellValue("Null--")
            titulo.getRow(9).createCell(6).setCellValue("Null--")
            titulo.getRow(9).createCell(7).setCellValue("Null--")
            titulo.getRow(9).createCell(8).setCellValue("Null--")
            titulo.getRow(9).createCell(9).setCellValue("Null--")
            titulo.getRow(9).createCell(10).cellStyle = estiloB
            titulo.createRow(10).createCell(0).setCellValue("Archivo:")
            titulo.getRow(10).createCell(2).setCellValue("Null--")
            titulo.getRow(10).createCell(3).setCellValue("Null--")
            titulo.getRow(10).createCell(4).setCellValue("Null--")
            titulo.getRow(10).createCell(5).setCellValue("Null--")
            titulo.getRow(10).createCell(6).setCellValue("Null--")
            titulo.getRow(10).createCell(7).setCellValue("Null--")
            titulo.getRow(10).createCell(8).setCellValue("Null--")
            titulo.getRow(10).createCell(9).setCellValue("Null--")
            titulo.getRow(10).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        11->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Crear Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).setCellValue("Valido")
            titulo.getRow(7).createCell(4).setCellValue("Valido")
            titulo.getRow(7).createCell(5).setCellValue("Valido")
            titulo.getRow(7).createCell(6).setCellValue("Valido")
            titulo.getRow(7).createCell(7).setCellValue("Valido")
            titulo.getRow(7).createCell(8).setCellValue("Valido")
            titulo.getRow(7).createCell(9).setCellValue("Valido")
            titulo.getRow(7).createCell(10).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("B Cancelar:")
            titulo.getRow(8).createCell(2).setCellValue("Fallo")
            titulo.getRow(8).createCell(3).setCellValue("Fallo")
            titulo.getRow(8).createCell(4).setCellValue("Fallo")
            titulo.getRow(8).createCell(5).setCellValue("Fallo")
            titulo.getRow(8).createCell(6).setCellValue("Fallo")
            titulo.getRow(8).createCell(7).setCellValue("Fallo")
            titulo.getRow(8).createCell(8).setCellValue("Fallo")
            titulo.getRow(8).createCell(9).setCellValue("Fallo")
            titulo.getRow(8).createCell(10).cellStyle = estiloR
            titulo.createRow(9).createCell(0).setCellValue("Crear Formulario:")
            titulo.getRow(9).createCell(2).setCellValue("Null--")
            titulo.getRow(9).createCell(3).setCellValue("Null--")
            titulo.getRow(9).createCell(4).setCellValue("Null--")
            titulo.getRow(9).createCell(5).setCellValue("Null--")
            titulo.getRow(9).createCell(6).setCellValue("Null--")
            titulo.getRow(9).createCell(7).setCellValue("Null--")
            titulo.getRow(9).createCell(8).setCellValue("Null--")
            titulo.getRow(9).createCell(9).setCellValue("Null--")
            titulo.getRow(9).createCell(10).cellStyle = estiloB
            titulo.createRow(10).createCell(0).setCellValue("Archivo:")
            titulo.getRow(10).createCell(2).setCellValue("Null--")
            titulo.getRow(10).createCell(3).setCellValue("Null--")
            titulo.getRow(10).createCell(4).setCellValue("Null--")
            titulo.getRow(10).createCell(5).setCellValue("Null--")
            titulo.getRow(10).createCell(6).setCellValue("Null--")
            titulo.getRow(10).createCell(7).setCellValue("Null--")
            titulo.getRow(10).createCell(8).setCellValue("Null--")
            titulo.getRow(10).createCell(9).setCellValue("Null--")
            titulo.getRow(10).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        12->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Crear Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).setCellValue("Valido")
            titulo.getRow(7).createCell(4).setCellValue("Valido")
            titulo.getRow(7).createCell(5).setCellValue("Valido")
            titulo.getRow(7).createCell(6).setCellValue("Valido")
            titulo.getRow(7).createCell(7).setCellValue("Valido")
            titulo.getRow(7).createCell(8).setCellValue("Valido")
            titulo.getRow(7).createCell(9).setCellValue("Valido")
            titulo.getRow(7).createCell(10).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("B Crear:")
            titulo.getRow(8).createCell(2).setCellValue("Fallo")
            titulo.getRow(8).createCell(3).setCellValue("Fallo")
            titulo.getRow(8).createCell(4).setCellValue("Fallo")
            titulo.getRow(8).createCell(5).setCellValue("Fallo")
            titulo.getRow(8).createCell(6).setCellValue("Fallo")
            titulo.getRow(8).createCell(7).setCellValue("Fallo")
            titulo.getRow(8).createCell(8).setCellValue("Fallo")
            titulo.getRow(8).createCell(9).setCellValue("Fallo")
            titulo.getRow(8).createCell(10).cellStyle = estiloR
            titulo.createRow(9).createCell(0).setCellValue("Alerta:")
            titulo.getRow(9).createCell(2).setCellValue("Fallo")
            titulo.getRow(9).createCell(3).setCellValue("Fallo")
            titulo.getRow(9).createCell(4).setCellValue("Fallo")
            titulo.getRow(9).createCell(5).setCellValue("Fallo")
            titulo.getRow(9).createCell(6).setCellValue("Fallo")
            titulo.getRow(9).createCell(7).setCellValue("Fallo")
            titulo.getRow(9).createCell(8).setCellValue("Fallo")
            titulo.getRow(9).createCell(9).setCellValue("Fallo")
            titulo.getRow(9).createCell(10).cellStyle = estiloR
            titulo.createRow(10).createCell(0).setCellValue("Archivo:")
            titulo.getRow(10).createCell(2).setCellValue("Null--")
            titulo.getRow(10).createCell(3).setCellValue("Null--")
            titulo.getRow(10).createCell(4).setCellValue("Null--")
            titulo.getRow(10).createCell(5).setCellValue("Null--")
            titulo.getRow(10).createCell(6).setCellValue("Null--")
            titulo.getRow(10).createCell(7).setCellValue("Null--")
            titulo.getRow(10).createCell(8).setCellValue("Null--")
            titulo.getRow(10).createCell(9).setCellValue("Null--")
            titulo.getRow(10).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        13->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Crear Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).setCellValue("Valido")
            titulo.getRow(7).createCell(4).setCellValue("Valido")
            titulo.getRow(7).createCell(5).setCellValue("Valido")
            titulo.getRow(7).createCell(6).setCellValue("Valido")
            titulo.getRow(7).createCell(7).setCellValue("Valido")
            titulo.getRow(7).createCell(8).setCellValue("Valido")
            titulo.getRow(7).createCell(9).setCellValue("Valido")
            titulo.getRow(7).createCell(10).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("B Crear:")
            titulo.getRow(8).createCell(2).setCellValue("Valido")
            titulo.getRow(8).createCell(3).setCellValue("Valido")
            titulo.getRow(8).createCell(4).setCellValue("Valido")
            titulo.getRow(8).createCell(5).setCellValue("Valido")
            titulo.getRow(8).createCell(6).setCellValue("Valido")
            titulo.getRow(8).createCell(7).setCellValue("Valido")
            titulo.getRow(8).createCell(8).setCellValue("Valido")
            titulo.getRow(8).createCell(9).setCellValue("Valido")
            titulo.getRow(8).createCell(10).cellStyle = estiloV
            titulo.createRow(9).createCell(0).setCellValue("Alerta:")
            titulo.getRow(9).createCell(2).setCellValue("Valido")
            titulo.getRow(9).createCell(3).setCellValue("Valido")
            titulo.getRow(9).createCell(4).setCellValue("Valido")
            titulo.getRow(9).createCell(5).setCellValue("Valido")
            titulo.getRow(9).createCell(6).setCellValue("Valido")
            titulo.getRow(9).createCell(7).setCellValue("Valido")
            titulo.getRow(9).createCell(8).setCellValue("Valido")
            titulo.getRow(9).createCell(9).setCellValue("Valido")
            titulo.getRow(9).createCell(10).cellStyle = estiloV
            titulo.createRow(10).createCell(0).setCellValue("B Regresar:")
            titulo.getRow(10).createCell(2).setCellValue("Fallo")
            titulo.getRow(10).createCell(3).setCellValue("Fallo")
            titulo.getRow(10).createCell(4).setCellValue("Fallo")
            titulo.getRow(10).createCell(5).setCellValue("Fallo")
            titulo.getRow(10).createCell(6).setCellValue("Fallo")
            titulo.getRow(10).createCell(7).setCellValue("Fallo")
            titulo.getRow(10).createCell(8).setCellValue("Fallo")
            titulo.getRow(10).createCell(9).setCellValue("Fallo")
            titulo.getRow(10).createCell(10).cellStyle = estiloR
            titulo.createRow(11).createCell(0).setCellValue("Archivo:")
            titulo.getRow(11).createCell(2).setCellValue("Null--")
            titulo.getRow(11).createCell(3).setCellValue("Null--")
            titulo.getRow(11).createCell(4).setCellValue("Null--")
            titulo.getRow(11).createCell(5).setCellValue("Null--")
            titulo.getRow(11).createCell(6).setCellValue("Null--")
            titulo.getRow(11).createCell(7).setCellValue("Null--")
            titulo.getRow(11).createCell(8).setCellValue("Null--")
            titulo.getRow(11).createCell(9).setCellValue("Null--")
            titulo.getRow(11).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        14->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Crear Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).setCellValue("Valido")
            titulo.getRow(7).createCell(4).setCellValue("Valido")
            titulo.getRow(7).createCell(5).setCellValue("Valido")
            titulo.getRow(7).createCell(6).setCellValue("Valido")
            titulo.getRow(7).createCell(7).setCellValue("Valido")
            titulo.getRow(7).createCell(8).setCellValue("Valido")
            titulo.getRow(7).createCell(9).setCellValue("Valido")
            titulo.getRow(7).createCell(10).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("B Crear:")
            titulo.getRow(8).createCell(2).setCellValue("Valido")
            titulo.getRow(8).createCell(3).setCellValue("Valido")
            titulo.getRow(8).createCell(4).setCellValue("Valido")
            titulo.getRow(8).createCell(5).setCellValue("Valido")
            titulo.getRow(8).createCell(6).setCellValue("Valido")
            titulo.getRow(8).createCell(7).setCellValue("Valido")
            titulo.getRow(8).createCell(8).setCellValue("Valido")
            titulo.getRow(8).createCell(9).setCellValue("Valido")
            titulo.getRow(8).createCell(10).cellStyle = estiloV
            titulo.createRow(9).createCell(0).setCellValue("Alerta:")
            titulo.getRow(9).createCell(2).setCellValue("Valido")
            titulo.getRow(9).createCell(3).setCellValue("Valido")
            titulo.getRow(9).createCell(4).setCellValue("Valido")
            titulo.getRow(9).createCell(5).setCellValue("Valido")
            titulo.getRow(9).createCell(6).setCellValue("Valido")
            titulo.getRow(9).createCell(7).setCellValue("Valido")
            titulo.getRow(9).createCell(8).setCellValue("Valido")
            titulo.getRow(9).createCell(9).setCellValue("Valido")
            titulo.getRow(9).createCell(10).cellStyle = estiloV
            titulo.createRow(10).createCell(0).setCellValue("Archivo:")
            titulo.getRow(10).createCell(2).setCellValue("Valido")
            titulo.getRow(10).createCell(3).setCellValue("Valido")
            titulo.getRow(10).createCell(4).setCellValue("Valido")
            titulo.getRow(10).createCell(5).setCellValue("Valido")
            titulo.getRow(10).createCell(6).setCellValue("Valido")
            titulo.getRow(10).createCell(7).setCellValue("Valido")
            titulo.getRow(10).createCell(8).setCellValue("Valido")
            titulo.getRow(10).createCell(9).setCellValue("Valido")
            titulo.getRow(10).createCell(10).cellStyle = estiloV
            titulo.createRow(11).createCell(0).setCellValue("B Subir Documento:")
            titulo.getRow(11).createCell(2).setCellValue("Fallo")
            titulo.getRow(11).createCell(3).setCellValue("Fallo")
            titulo.getRow(11).createCell(4).setCellValue("Fallo")
            titulo.getRow(11).createCell(5).setCellValue("Fallo")
            titulo.getRow(11).createCell(6).setCellValue("Fallo")
            titulo.getRow(11).createCell(7).setCellValue("Fallo")
            titulo.getRow(11).createCell(8).setCellValue("Fallo")
            titulo.getRow(11).createCell(9).setCellValue("Fallo")
            titulo.getRow(11).createCell(10).cellStyle = estiloR
            titulo.createRow(12).createCell(0).setCellValue("Alerta1:")
            titulo.getRow(12).createCell(2).setCellValue("Fallo")
            titulo.getRow(12).createCell(3).setCellValue("Fallo")
            titulo.getRow(12).createCell(4).setCellValue("Fallo")
            titulo.getRow(12).createCell(5).setCellValue("Fallo")
            titulo.getRow(12).createCell(6).setCellValue("Fallo")
            titulo.getRow(12).createCell(7).setCellValue("Fallo")
            titulo.getRow(12).createCell(8).setCellValue("Fallo")
            titulo.getRow(12).createCell(9).setCellValue("Fallo")
            titulo.getRow(12).createCell(10).cellStyle = estiloR
            titulo.createRow(13).createCell(0).setCellValue("Alerta2:")
            titulo.getRow(13).createCell(2).setCellValue("Fallo")
            titulo.getRow(13).createCell(3).setCellValue("Fallo")
            titulo.getRow(13).createCell(4).setCellValue("Fallo")
            titulo.getRow(13).createCell(5).setCellValue("Fallo")
            titulo.getRow(13).createCell(6).setCellValue("Fallo")
            titulo.getRow(13).createCell(7).setCellValue("Fallo")
            titulo.getRow(13).createCell(8).setCellValue("Fallo")
            titulo.getRow(13).createCell(9).setCellValue("Fallo")
            titulo.getRow(13).createCell(10).cellStyle = estiloR
            titulo.createRow(14).createCell(0).setCellValue("Subir Documento:")
            titulo.getRow(14).createCell(2).setCellValue("Fallo")
            titulo.getRow(14).createCell(3).setCellValue("Fallo")
            titulo.getRow(14).createCell(4).setCellValue("Fallo")
            titulo.getRow(14).createCell(5).setCellValue("Fallo")
            titulo.getRow(14).createCell(6).setCellValue("Fallo")
            titulo.getRow(14).createCell(7).setCellValue("Fallo")
            titulo.getRow(14).createCell(8).setCellValue("Fallo")
            titulo.getRow(14).createCell(9).setCellValue("Fallo")
            titulo.getRow(14).createCell(10).cellStyle = estiloR
            dato.write(output)
            dato.close()
        }
        15->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Crear Formulario:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Formulario:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).setCellValue("Valido")
            titulo.getRow(7).createCell(4).setCellValue("Valido")
            titulo.getRow(7).createCell(5).setCellValue("Valido")
            titulo.getRow(7).createCell(6).setCellValue("Valido")
            titulo.getRow(7).createCell(7).setCellValue("Valido")
            titulo.getRow(7).createCell(8).setCellValue("Valido")
            titulo.getRow(7).createCell(9).setCellValue("Valido")
            titulo.getRow(7).createCell(10).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("B Crear:")
            titulo.getRow(8).createCell(2).setCellValue("Valido")
            titulo.getRow(8).createCell(3).setCellValue("Valido")
            titulo.getRow(8).createCell(4).setCellValue("Valido")
            titulo.getRow(8).createCell(5).setCellValue("Valido")
            titulo.getRow(8).createCell(6).setCellValue("Valido")
            titulo.getRow(8).createCell(7).setCellValue("Valido")
            titulo.getRow(8).createCell(8).setCellValue("Valido")
            titulo.getRow(8).createCell(9).setCellValue("Valido")
            titulo.getRow(8).createCell(10).cellStyle = estiloV
            titulo.createRow(9).createCell(0).setCellValue("Alerta:")
            titulo.getRow(9).createCell(2).setCellValue("Valido")
            titulo.getRow(9).createCell(3).setCellValue("Valido")
            titulo.getRow(9).createCell(4).setCellValue("Valido")
            titulo.getRow(9).createCell(5).setCellValue("Valido")
            titulo.getRow(9).createCell(6).setCellValue("Valido")
            titulo.getRow(9).createCell(7).setCellValue("Valido")
            titulo.getRow(9).createCell(8).setCellValue("Valido")
            titulo.getRow(9).createCell(9).setCellValue("Valido")
            titulo.getRow(9).createCell(10).cellStyle = estiloV
            titulo.createRow(10).createCell(0).setCellValue("Archivo:")
            titulo.getRow(10).createCell(2).setCellValue("Valido")
            titulo.getRow(10).createCell(3).setCellValue("Valido")
            titulo.getRow(10).createCell(4).setCellValue("Valido")
            titulo.getRow(10).createCell(5).setCellValue("Valido")
            titulo.getRow(10).createCell(6).setCellValue("Valido")
            titulo.getRow(10).createCell(7).setCellValue("Valido")
            titulo.getRow(10).createCell(8).setCellValue("Valido")
            titulo.getRow(10).createCell(9).setCellValue("Valido")
            titulo.getRow(10).createCell(10).cellStyle = estiloV
            titulo.createRow(11).createCell(0).setCellValue("B Subir Documento:")
            titulo.getRow(11).createCell(2).setCellValue("Valido")
            titulo.getRow(11).createCell(3).setCellValue("Valido")
            titulo.getRow(11).createCell(4).setCellValue("Valido")
            titulo.getRow(11).createCell(5).setCellValue("Valido")
            titulo.getRow(11).createCell(6).setCellValue("Valido")
            titulo.getRow(11).createCell(7).setCellValue("Valido")
            titulo.getRow(11).createCell(8).setCellValue("Valido")
            titulo.getRow(11).createCell(9).setCellValue("Valido")
            titulo.getRow(11).createCell(10).cellStyle = estiloV
            titulo.createRow(12).createCell(0).setCellValue("Alerta1:")
            titulo.getRow(12).createCell(2).setCellValue("Valido")
            titulo.getRow(12).createCell(3).setCellValue("Valido")
            titulo.getRow(12).createCell(4).setCellValue("Valido")
            titulo.getRow(12).createCell(5).setCellValue("Valido")
            titulo.getRow(12).createCell(6).setCellValue("Valido")
            titulo.getRow(12).createCell(7).setCellValue("Valido")
            titulo.getRow(12).createCell(8).setCellValue("Valido")
            titulo.getRow(12).createCell(9).setCellValue("Valido")
            titulo.getRow(12).createCell(10).cellStyle = estiloV
            titulo.createRow(13).createCell(0).setCellValue("Alerta2:")
            titulo.getRow(13).createCell(2).setCellValue("Valido")
            titulo.getRow(13).createCell(3).setCellValue("Valido")
            titulo.getRow(13).createCell(4).setCellValue("Valido")
            titulo.getRow(13).createCell(5).setCellValue("Valido")
            titulo.getRow(13).createCell(6).setCellValue("Valido")
            titulo.getRow(13).createCell(7).setCellValue("Valido")
            titulo.getRow(13).createCell(8).setCellValue("Valido")
            titulo.getRow(13).createCell(9).setCellValue("Valido")
            titulo.getRow(13).createCell(10).cellStyle = estiloV
            titulo.createRow(14).createCell(0).setCellValue("Subir Documento:")
            titulo.getRow(14).createCell(2).setCellValue("Fallo")
            titulo.getRow(14).createCell(3).setCellValue("Fallo")
            titulo.getRow(14).createCell(4).setCellValue("Fallo")
            titulo.getRow(14).createCell(5).setCellValue("Fallo")
            titulo.getRow(14).createCell(6).setCellValue("Fallo")
            titulo.getRow(14).createCell(7).setCellValue("Fallo")
            titulo.getRow(14).createCell(8).setCellValue("Fallo")
            titulo.getRow(14).createCell(9).setCellValue("Fallo")
            titulo.getRow(14).createCell(10).cellStyle = estiloR
            dato.write(output)
            dato.close()
        }
        16->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Buscar Expediente:")
            titulo.getRow(6).createCell(2).setCellValue("Fallo")
            titulo.getRow(6).createCell(3).setCellValue("Fallo")
            titulo.getRow(6).createCell(4).setCellValue("Fallo")
            titulo.getRow(6).createCell(5).setCellValue("Fallo")
            titulo.getRow(6).createCell(6).setCellValue("Fallo")
            titulo.getRow(6).createCell(7).setCellValue("Fallo")
            titulo.getRow(6).createCell(8).setCellValue("Fallo")
            titulo.getRow(6).createCell(9).setCellValue("Fallo")
            titulo.getRow(6).createCell(10).cellStyle = estiloR
            titulo.createRow(7).createCell(0).setCellValue("Archivo:")
            titulo.getRow(7).createCell(2).setCellValue("Null--")
            titulo.getRow(7).createCell(3).setCellValue("Null--")
            titulo.getRow(7).createCell(4).setCellValue("Null--")
            titulo.getRow(7).createCell(5).setCellValue("Null--")
            titulo.getRow(7).createCell(6).setCellValue("Null--")
            titulo.getRow(7).createCell(7).setCellValue("Null--")
            titulo.getRow(7).createCell(8).setCellValue("Null--")
            titulo.getRow(7).createCell(9).setCellValue("Null--")
            titulo.getRow(7).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()

        }
        17->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Buscar Expediente:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Archivo:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).setCellValue("Valido")
            titulo.getRow(7).createCell(4).setCellValue("Valido")
            titulo.getRow(7).createCell(5).setCellValue("Valido")
            titulo.getRow(7).createCell(6).setCellValue("Valido")
            titulo.getRow(7).createCell(7).setCellValue("Valido")
            titulo.getRow(7).createCell(8).setCellValue("Valido")
            titulo.getRow(7).createCell(9).setCellValue("Valido")
            titulo.getRow(7).createCell(10).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("B Subir Documento:")
            titulo.getRow(8).createCell(2).setCellValue("Fallo")
            titulo.getRow(8).createCell(3).setCellValue("Fallo")
            titulo.getRow(8).createCell(4).setCellValue("Fallo")
            titulo.getRow(8).createCell(5).setCellValue("Fallo")
            titulo.getRow(8).createCell(6).setCellValue("Fallo")
            titulo.getRow(8).createCell(7).setCellValue("Fallo")
            titulo.getRow(8).createCell(8).setCellValue("Fallo")
            titulo.getRow(8).createCell(9).setCellValue("Fallo")
            titulo.getRow(8).createCell(10).cellStyle = estiloR
            titulo.createRow(9).createCell(0).setCellValue("Alerta1:")
            titulo.getRow(9).createCell(2).setCellValue("Fallo")
            titulo.getRow(9).createCell(3).setCellValue("Fallo")
            titulo.getRow(9).createCell(4).setCellValue("Fallo")
            titulo.getRow(9).createCell(5).setCellValue("Fallo")
            titulo.getRow(9).createCell(6).setCellValue("Fallo")
            titulo.getRow(9).createCell(7).setCellValue("Fallo")
            titulo.getRow(9).createCell(8).setCellValue("Fallo")
            titulo.getRow(9).createCell(9).setCellValue("Fallo")
            titulo.getRow(9).createCell(10).cellStyle = estiloR
            titulo.createRow(10).createCell(0).setCellValue("Alerta2:")
            titulo.getRow(10).createCell(2).setCellValue("Null---")
            titulo.getRow(10).createCell(3).setCellValue("Null---")
            titulo.getRow(10).createCell(4).setCellValue("Null---")
            titulo.getRow(10).createCell(5).setCellValue("Null---")
            titulo.getRow(10).createCell(6).setCellValue("Null---")
            titulo.getRow(10).createCell(7).setCellValue("Null---")
            titulo.getRow(10).createCell(8).setCellValue("Null---")
            titulo.getRow(10).createCell(9).setCellValue("Null---")
            titulo.getRow(10).createCell(10).cellStyle = estiloB
            titulo.createRow(11).createCell(0).setCellValue("Subir Documento:")
            titulo.getRow(11).createCell(2).setCellValue("Null---")
            titulo.getRow(11).createCell(3).setCellValue("Null---")
            titulo.getRow(11).createCell(4).setCellValue("Null---")
            titulo.getRow(11).createCell(5).setCellValue("Null---")
            titulo.getRow(11).createCell(6).setCellValue("Null---")
            titulo.getRow(11).createCell(7).setCellValue("Null---")
            titulo.getRow(11).createCell(8).setCellValue("Null---")
            titulo.getRow(11).createCell(9).setCellValue("Null---")
            titulo.getRow(11).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        18->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Buscar Expediente:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Archivo:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).setCellValue("Valido")
            titulo.getRow(7).createCell(4).setCellValue("Valido")
            titulo.getRow(7).createCell(5).setCellValue("Valido")
            titulo.getRow(7).createCell(6).setCellValue("Valido")
            titulo.getRow(7).createCell(7).setCellValue("Valido")
            titulo.getRow(7).createCell(8).setCellValue("Valido")
            titulo.getRow(7).createCell(9).setCellValue("Valido")
            titulo.getRow(7).createCell(10).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("B Subir Documento:")
            titulo.getRow(8).createCell(2).setCellValue("Valido")
            titulo.getRow(8).createCell(3).setCellValue("Valido")
            titulo.getRow(8).createCell(4).setCellValue("Valido")
            titulo.getRow(8).createCell(5).setCellValue("Valido")
            titulo.getRow(8).createCell(6).setCellValue("Valido")
            titulo.getRow(8).createCell(7).setCellValue("Valido")
            titulo.getRow(8).createCell(8).setCellValue("Valido")
            titulo.getRow(8).createCell(9).setCellValue("Valido")
            titulo.getRow(8).createCell(10).cellStyle = estiloV
            titulo.createRow(9).createCell(0).setCellValue("Alerta1:")
            titulo.getRow(9).createCell(2).setCellValue("Valido")
            titulo.getRow(9).createCell(3).setCellValue("Valido")
            titulo.getRow(9).createCell(4).setCellValue("Valido")
            titulo.getRow(9).createCell(5).setCellValue("Valido")
            titulo.getRow(9).createCell(6).setCellValue("Valido")
            titulo.getRow(9).createCell(7).setCellValue("Valido")
            titulo.getRow(9).createCell(8).setCellValue("Valido")
            titulo.getRow(9).createCell(9).setCellValue("Valido")
            titulo.getRow(9).createCell(10).cellStyle = estiloV
            titulo.createRow(10).createCell(0).setCellValue("Alerta2:")
            titulo.getRow(10).createCell(2).setCellValue("Fallo")
            titulo.getRow(10).createCell(3).setCellValue("Fallo")
            titulo.getRow(10).createCell(4).setCellValue("Fallo")
            titulo.getRow(10).createCell(5).setCellValue("Fallo")
            titulo.getRow(10).createCell(6).setCellValue("Fallo")
            titulo.getRow(10).createCell(7).setCellValue("Fallo")
            titulo.getRow(10).createCell(8).setCellValue("Fallo")
            titulo.getRow(10).createCell(9).setCellValue("Fallo")
            titulo.getRow(10).createCell(10).cellStyle = estiloR
            titulo.createRow(11).createCell(0).setCellValue("Subir Documento:")
            titulo.getRow(11).createCell(2).setCellValue("Null---")
            titulo.getRow(11).createCell(3).setCellValue("Null---")
            titulo.getRow(11).createCell(4).setCellValue("Null---")
            titulo.getRow(11).createCell(5).setCellValue("Null---")
            titulo.getRow(11).createCell(6).setCellValue("Null---")
            titulo.getRow(11).createCell(7).setCellValue("Null---")
            titulo.getRow(11).createCell(8).setCellValue("Null---")
            titulo.getRow(11).createCell(9).setCellValue("Null---")
            titulo.getRow(11).createCell(10).cellStyle = estiloB
            dato.write(output)
            dato.close()
        }
        19->{
            titulo.createRow(0).createCell(1).setCellValue("Reporte del sistema: URIDEC")
            titulo.createRow(2).createCell(0).setCellValue("Prueba:")
            titulo.getRow(2).createCell(1).setCellValue(prueba)
            titulo.createRow(3).createCell(2).setCellValue("prueba 1")
            titulo.getRow(3).createCell(3).setCellValue("prueba 2")
            titulo.getRow(3).createCell(4).setCellValue("prueba 3")
            titulo.getRow(3).createCell(5).setCellValue("prueba 4")
            titulo.getRow(3).createCell(6).setCellValue("prueba 5")
            titulo.getRow(3).createCell(7).setCellValue("prueba 6")
            titulo.getRow(3).createCell(8).setCellValue("prueba 7")
            titulo.getRow(3).createCell(9).setCellValue("prueba 8")
            titulo.createRow(4).createCell(0).setCellValue("Login:")
            titulo.getRow(4).createCell(2).setCellValue("Valido")
            titulo.getRow(4).createCell(3).setCellValue("Valido")
            titulo.getRow(4).createCell(4).setCellValue("Valido")
            titulo.getRow(4).createCell(5).setCellValue("Valido")
            titulo.getRow(4).createCell(6).setCellValue("Valido")
            titulo.getRow(4).createCell(7).setCellValue("Valido")
            titulo.getRow(4).createCell(8).setCellValue("Valido")
            titulo.getRow(4).createCell(9).setCellValue("Valido")
            titulo.getRow(4).createCell(10).cellStyle = estiloV
            titulo.createRow(5).createCell(0).setCellValue("Opciones:")
            titulo.getRow(5).createCell(2).setCellValue("Valido")
            titulo.getRow(5).createCell(3).setCellValue("Valido")
            titulo.getRow(5).createCell(4).setCellValue("Valido")
            titulo.getRow(5).createCell(5).setCellValue("Valido")
            titulo.getRow(5).createCell(6).setCellValue("Valido")
            titulo.getRow(5).createCell(7).setCellValue("Valido")
            titulo.getRow(5).createCell(8).setCellValue("Valido")
            titulo.getRow(5).createCell(9).setCellValue("Valido")
            titulo.getRow(5).createCell(10).cellStyle = estiloV
            titulo.createRow(6).createCell(0).setCellValue("B Buscar Expediente:")
            titulo.getRow(6).createCell(2).setCellValue("Valido")
            titulo.getRow(6).createCell(3).setCellValue("Valido")
            titulo.getRow(6).createCell(4).setCellValue("Valido")
            titulo.getRow(6).createCell(5).setCellValue("Valido")
            titulo.getRow(6).createCell(6).setCellValue("Valido")
            titulo.getRow(6).createCell(7).setCellValue("Valido")
            titulo.getRow(6).createCell(8).setCellValue("Valido")
            titulo.getRow(6).createCell(9).setCellValue("Valido")
            titulo.getRow(6).createCell(10).cellStyle = estiloV
            titulo.createRow(7).createCell(0).setCellValue("Archivo:")
            titulo.getRow(7).createCell(2).setCellValue("Valido")
            titulo.getRow(7).createCell(3).setCellValue("Valido")
            titulo.getRow(7).createCell(4).setCellValue("Valido")
            titulo.getRow(7).createCell(5).setCellValue("Valido")
            titulo.getRow(7).createCell(6).setCellValue("Valido")
            titulo.getRow(7).createCell(7).setCellValue("Valido")
            titulo.getRow(7).createCell(8).setCellValue("Valido")
            titulo.getRow(7).createCell(9).setCellValue("Valido")
            titulo.getRow(7).createCell(10).cellStyle = estiloV
            titulo.createRow(8).createCell(0).setCellValue("B Subir Documento:")
            titulo.getRow(8).createCell(2).setCellValue("Valido")
            titulo.getRow(8).createCell(3).setCellValue("Valido")
            titulo.getRow(8).createCell(4).setCellValue("Valido")
            titulo.getRow(8).createCell(5).setCellValue("Valido")
            titulo.getRow(8).createCell(6).setCellValue("Valido")
            titulo.getRow(8).createCell(7).setCellValue("Valido")
            titulo.getRow(8).createCell(8).setCellValue("Valido")
            titulo.getRow(8).createCell(9).setCellValue("Valido")
            titulo.getRow(8).createCell(10).cellStyle = estiloV
            titulo.createRow(9).createCell(0).setCellValue("Alerta1:")
            titulo.getRow(9).createCell(2).setCellValue("Valido")
            titulo.getRow(9).createCell(3).setCellValue("Valido")
            titulo.getRow(9).createCell(4).setCellValue("Valido")
            titulo.getRow(9).createCell(5).setCellValue("Valido")
            titulo.getRow(9).createCell(6).setCellValue("Valido")
            titulo.getRow(9).createCell(7).setCellValue("Valido")
            titulo.getRow(9).createCell(8).setCellValue("Valido")
            titulo.getRow(9).createCell(9).setCellValue("Valido")
            titulo.getRow(9).createCell(10).cellStyle = estiloV
            titulo.createRow(10).createCell(0).setCellValue("Alerta2:")
            titulo.getRow(10).createCell(2).setCellValue("Valido")
            titulo.getRow(10).createCell(3).setCellValue("Valido")
            titulo.getRow(10).createCell(4).setCellValue("Valido")
            titulo.getRow(10).createCell(5).setCellValue("Valido")
            titulo.getRow(10).createCell(6).setCellValue("Valido")
            titulo.getRow(10).createCell(7).setCellValue("Valido")
            titulo.getRow(10).createCell(8).setCellValue("Valido")
            titulo.getRow(10).createCell(9).setCellValue("Valido")
            titulo.getRow(10).createCell(10).cellStyle = estiloV
            titulo.createRow(11).createCell(0).setCellValue("Subir Documento:")
            titulo.getRow(11).createCell(2).setCellValue("Valido")
            titulo.getRow(11).createCell(3).setCellValue("Valido")
            titulo.getRow(11).createCell(4).setCellValue("Valido")
            titulo.getRow(11).createCell(5).setCellValue("Valido")
            titulo.getRow(11).createCell(6).setCellValue("Valido")
            titulo.getRow(11).createCell(7).setCellValue("Valido")
            titulo.getRow(11).createCell(8).setCellValue("Valido")
            titulo.getRow(11).createCell(9).setCellValue("Valido")
            titulo.getRow(11).createCell(10).cellStyle = estiloV
            dato.write(output)
            dato.close()
        }
    }
}